{
    "openapi": "3.0.0",
    "info": {
        "title": "Träwelling API",
        "description": "Träwelling user API description. This is an incomplete documentation with still many errors. The API is currently not yet stable. Endpoints are still being restructured. Both the URL and the request or body can be changed. Breaking changes will be announced on GitHub: https://github.com/Traewelling/traewelling/blob/develop/API_CHANGELOG.md",
        "contact": {
            "email": "support@traewelling.de"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0 - alpha"
    },
    "servers": [
        {
            "url": "https://traewelling.de/api/v1",
            "description": "Production Server"
        },
        {
            "url": "http://localhost:8000/api/v1",
            "description": "This instance"
        }
    ],
    "paths": {
        "/auth/logout": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Logout & invalidate current bearer token",
                "operationId": "logoutUser",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/auth/user": {
            "get": {
                "tags": [
                    "Auth",
                    "User"
                ],
                "summary": "Get authenticated user information",
                "description": "Get all profile information about the authenticated user",
                "operationId": "getAuthenticatedUser",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/auth/refresh": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh Bearer Token",
                "description": "This request issues a new Bearer-Token with a new expiration date while also revoking the old\n     *      token.",
                "operationId": "refreshToken",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/event/{slug}": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "[Auth optional] Get basic information for event",
                "description": "Returns slug, name and duration for an event",
                "operationId": "getEvent",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/event/{slug}/details": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "[Auth optional] Get additional information for event",
                "description": "Returns overall travelled distance and duration for an event",
                "operationId": "getEventDetails",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/event/{slug}/statuses": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "[Auth optional] Get paginated statuses for event",
                "description": "Returns all for user visible statuses for an event",
                "operationId": "getEventStatuses",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/events": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "[Auth optional] Show active or upcoming events for the given timestamp",
                "description": "Returns all active or upcoming events for the given timestamp. Default timestamp is now. If upcoming is set to true, all events ending after the timestamp are returned.",
                "operationId": "getEvents",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/event": {
            "post": {
                "tags": [
                    "Events"
                ],
                "summary": "Suggest a event",
                "description": "Submit a possible event for our administrators to publish",
                "operationId": "suggestEvent",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/activeEvents": {
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "DEPRECATED - USE /events - removed after 2024-08",
                "description": "DEPRECATED - USE /events - removed after 2024-08",
                "operationId": "getActiveEvents"
            }
        },
        "/user/{id}/follow": {
            "post": {
                "tags": [
                    "User/Follow"
                ],
                "summary": "Follow a user",
                "operationId": "createFollow",
                "security": [
                    {
                        "passport": [
                            "write-follows"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User/Follow"
                ],
                "summary": "Unfollow a user",
                "operationId": "destroyFollow",
                "security": [
                    {
                        "passport": [
                            "write-follows"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/self/followers": {
            "get": {
                "tags": [
                    "User/Follow",
                    "Settings"
                ],
                "summary": "List all followers",
                "operationId": "getFollowers",
                "security": [
                    {
                        "passport": [
                            "read-settings-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/self/follow-requests": {
            "get": {
                "tags": [
                    "User/Follow",
                    "Settings"
                ],
                "summary": "List all followers",
                "operationId": "getFollowRequests",
                "security": [
                    {
                        "passport": [
                            "read-settings-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/self/followings": {
            "get": {
                "tags": [
                    "User/Follow",
                    "Settings"
                ],
                "summary": "List all users the current user is following",
                "operationId": "getFollowings",
                "security": [
                    {
                        "passport": [
                            "read-settings-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/self/followers/{userId}": {
            "delete": {
                "tags": [
                    "User/Follow"
                ],
                "summary": "Remove a follower",
                "operationId": "removeFollower",
                "security": [
                    {
                        "passport": [
                            "write-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/self/follow-requests/{userId}": {
            "put": {
                "tags": [
                    "User/Follow"
                ],
                "summary": "Accept a follow request",
                "operationId": "acceptFollowRequest",
                "security": [
                    {
                        "passport": [
                            "write-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User/Follow"
                ],
                "summary": "Reject a follow request",
                "operationId": "rejectFollowRequest",
                "security": [
                    {
                        "passport": [
                            "write-followers"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/status/{id}/likes": {
            "get": {
                "tags": [
                    "Likes"
                ],
                "summary": "[Auth optional] Get likes for status",
                "description": "Returns array of users that liked the status. Can return an empty dataset when the status\n     *      author or the requesting user has deactivated likes",
                "operationId": "getLikesForStatus",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/status/{id}/like": {
            "post": {
                "tags": [
                    "Likes"
                ],
                "summary": "Add like to status",
                "description": "Add like to status",
                "operationId": "addLikeToStatus",
                "security": [
                    {
                        "passport": [
                            "write-likes"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Likes"
                ],
                "summary": "Remove like from status",
                "description": "Removes like from status",
                "operationId": "removeLikeFromStatus",
                "security": [
                    {
                        "passport": [
                            "write-likes"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/notifications/unread/count": {
            "get": {
                "tags": [
                    "Notifications"
                ],
                "summary": "Get count of unread notifications for authenticated user",
                "description": "Returns count of unread notifications of a authenticated user",
                "operationId": "getUnreadCount",
                "security": [
                    {
                        "passport": [
                            "read-notifications"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/notifications": {
            "get": {
                "tags": [
                    "Notifications"
                ],
                "summary": "Get paginated notifications for authenticated user",
                "description": "Returns paginated notifications of a authenticated",
                "operationId": "listNotifications",
                "security": [
                    {
                        "passport": [
                            "read-notifications"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/notifications/read/{id}": {
            "put": {
                "tags": [
                    "Notifications"
                ],
                "summary": "Mark notification as read",
                "operationId": "markAsRead",
                "security": [
                    {
                        "passport": [
                            "write-notifications"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/notifications/unread/{id}": {
            "put": {
                "tags": [
                    "Notifications"
                ],
                "summary": "Mark notification as unread",
                "operationId": "markAsUnread",
                "security": [
                    {
                        "passport": [
                            "write-notifications"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/notifications/read/all": {
            "put": {
                "tags": [
                    "Notifications"
                ],
                "summary": "Mark all notification as read",
                "operationId": "markAllAsRead",
                "security": [
                    {
                        "passport": [
                            "write-notifications"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/operators": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Get a list of all operators.",
                "operationId": "bcfcf8686980cf0fcdc751b2e13fa4f7"
            }
        },
        "/static/privacy": {
            "get": {
                "tags": [
                    "Settings"
                ],
                "summary": "Get the current privacy policy",
                "description": "Get the current privacy policy",
                "operationId": "e649bec35ba50765db023e745233eda9"
            }
        },
        "/settings/acceptPrivacy": {
            "post": {
                "tags": [
                    "Settings"
                ],
                "summary": "Accept the current privacy policy",
                "description": "Accept the current privacy policy",
                "operationId": "acceptPrivacyPolicy",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/report": {
            "post": {
                "tags": [
                    "Report"
                ],
                "summary": "Report a Status, Event or User to the admins.",
                "operationId": "report",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/settings/profile": {
            "get": {
                "tags": [
                    "Settings"
                ],
                "summary": "Get the current user's profile settings",
                "description": "Get the current user's profile settings",
                "operationId": "getProfileSettings",
                "security": [
                    {
                        "passport": [
                            "read-settings"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Settings"
                ],
                "summary": "Update the current user's profile settings",
                "description": "Update the current user's profile settings",
                "operationId": "updateProfileSettings",
                "security": [
                    {
                        "passport": [
                            "write-settings"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/stations": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Search for stations",
                "description": "UNSTABLE: This request returns an array of max. 20 station objects matching the query. **CAUTION:** All\n     *      slashes (as well as encoded to %2F) in {query} need to be replaced, preferrably by a space (%20)",
                "operationId": "indexStation",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/leaderboard": {
            "get": {
                "tags": [
                    "Leaderboard"
                ],
                "summary": "[Auth optional] Get array of 20 best users",
                "operationId": "getLeaderboard",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/leaderboard/distance": {
            "get": {
                "tags": [
                    "Leaderboard"
                ],
                "summary": "[Auth optional] Get leaderboard array sorted by distance",
                "operationId": "getLeaderboardByDistance",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/leaderboard/friends": {
            "get": {
                "tags": [
                    "Leaderboard"
                ],
                "summary": "Get friends-leaderboard array sorted",
                "operationId": "getLeaderboardByFriends",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/leaderboard/{month}": {
            "get": {
                "tags": [
                    "Leaderboard"
                ],
                "summary": "[Auth optional] Get leaderboard array for a specific month",
                "operationId": "getMonthlyLeaderboard",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/statistics": {
            "get": {
                "tags": [
                    "Statistics"
                ],
                "summary": "Get personal statistics",
                "operationId": "getStatistics",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/statistics/daily/{date}": {
            "get": {
                "tags": [
                    "Statistics"
                ],
                "summary": "Get statistics and statuses of one day",
                "description": "Returns all statuses and statistics for the requested day",
                "operationId": "getDailyStatistics",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/statistics/global": {
            "get": {
                "tags": [
                    "Statistics"
                ],
                "summary": "Get global statistics of the last 4 weeks",
                "operationId": "getGlobalStatistics",
                "security": [
                    {
                        "passport": [
                            "read-statistics"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/dashboard": {
            "get": {
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get paginated statuses of personal dashboard",
                "description": "Returns paginated statuses of personal dashboard",
                "operationId": "getDashboard",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/dashboard/global": {
            "get": {
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get paginated statuses of global dashboard",
                "description": "Returns paginated statuses of global dashboard",
                "operationId": "getGlobalDashboard",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/dashboard/future": {
            "get": {
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get paginated future statuses of current user",
                "description": "Returns paginated statuses of the authenticated user, that are more than 20 minutes in the\n     *      future",
                "operationId": "getFutureDashboard",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/statuses": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] Get active statuses",
                "description": "Returns all currently active statuses that are visible to the (un)authenticated user",
                "operationId": "getActiveStatuses",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/positions": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] get live positions for active statuses",
                "description": "Returns an array of live position objects for active statuses",
                "operationId": "getLivePositionsForActiveStatuses",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/positions/{ids}": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] get live positions for given statuses",
                "description": "Returns an array of live position objects for given status IDs",
                "operationId": "getLivePositionsForStatuses",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/status/{id}": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] Get single statuses",
                "description": "Returns a single status Object, if user is authorized to see it",
                "operationId": "getSingleStatus",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Status"
                ],
                "summary": "Update a status",
                "description": "Updates a single status Object, if user is authorized to",
                "operationId": "updateSingleStatus",
                "security": [
                    {
                        "passport": [
                            "write-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Status"
                ],
                "summary": "Destroy a status",
                "description": "Deletes a single status Object, if user is authorized to",
                "operationId": "destroySingleStatus",
                "security": [
                    {
                        "passport": [
                            "write-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/polyline/{ids}": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] Get GeoJSON for statuses",
                "description": "Returns GeoJSON for all requested status IDs",
                "operationId": "getPolylines",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/stopovers/{ids}": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "[Auth optional] Get stopovers for statuses",
                "description": "Returns all underway-stops for stations",
                "operationId": "getStopOvers",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/statuses/active": {
            "get": {
                "tags": [
                    "Auth"
                ],
                "summary": "User state",
                "description": "This request returns whether the currently logged-in user has an active check-in or not.",
                "operationId": "userState",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/status/{statusId}/tags": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Show all tags for a status which are visible for the current user",
                "description": "Returns a collection of all visible tags for the given status, if user is authorized",
                "operationId": "getTagsForStatus",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Status"
                ],
                "summary": "Create a StatusTag",
                "description": "Creates a single StatusTag Object, if user is authorized to. <br><br>The key of a tag is free\n     *      text. You can choose it as you need it. However, <b>please use a namespace for tags</b>\n     *      (<i>namespace:xxx</i>) that only affect your own application.<br><br>For tags related to standard actions\n     *      we recommend the following tags in the trwl namespace:<br>\n     *      <ul>\n     *          <li>trwl:seat (i.e. 61)</li>\n     *          <[...]",
                "operationId": "createSingleStatusTag",
                "security": [
                    {
                        "passport": [
                            "write-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/statuses/{statusIds}/tags": {
            "get": {
                "tags": [
                    "Status"
                ],
                "summary": "Show all tags for multiple statuses which are visible for the current user",
                "description": "Returns a collection of all visible tags for the given statuses, if user is authorized",
                "operationId": "getTagsForMultipleStatuses",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/status/{statusId}/tags/{tagKey}": {
            "put": {
                "tags": [
                    "Status"
                ],
                "summary": "Update a StatusTag",
                "description": "Updates a single StatusTag Object, if user is authorized to",
                "operationId": "updateSingleStatusTag",
                "security": [
                    {
                        "passport": [
                            "write-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Status"
                ],
                "summary": "Destroy a StatusTag",
                "description": "Deletes a single StatusTag Object, if user is authorized to",
                "operationId": "destroySingleStatusTag",
                "security": [
                    {
                        "passport": [
                            "write-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/station/{id}/departures": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Get departures from a station",
                "description": "Get departures from a station.",
                "operationId": "getDepartures",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/trains/trip": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Get the stopovers and trip information for a given train",
                "operationId": "getTrainTrip",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/trains/station/nearby": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Location based search for stations",
                "description": "Returns the nearest station to the given coordinates",
                "operationId": "trainStationsNearby",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/trains/checkin": {
            "post": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Check in to a trip.",
                "operationId": "createCheckin",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/station/{id}/home": {
            "put": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Set a station as home station",
                "operationId": "setHomeStation",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/trains/station/autocomplete/{query}": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "Autocomplete for stations",
                "description": "This request returns an array of max. 10 station objects matching the query. **CAUTION:** All\n     *      slashes (as well as encoded to %2F) in {query} need to be replaced, preferrably by a space (%20)",
                "operationId": "trainStationAutocomplete",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/trains/station/history": {
            "get": {
                "tags": [
                    "Checkin"
                ],
                "summary": "History for stations",
                "description": "This request returns an array of max. 10 most recent station objects that the user has arrived\n     *      at.",
                "operationId": "trainStationHistory",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/{user}/trusted": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get all trusted users for a user",
                "description": "Get all trusted users for the current user or a specific user (admin only).",
                "operationId": "trustedUserIndex"
            },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Add a user to the trusted users for a user",
                "description": "Add a user to the trusted users for the current user or a specific user (admin only).",
                "operationId": "trustedUserStore"
            }
        },
        "/user/self/trusted-by": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get all users who trust the current user",
                "operationId": "trustedByUserIndex"
            }
        },
        "/user/{user}/trusted/{trusted}": {
            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Remove a user from the trusted users for a user",
                "description": "Remove a user from the trusted users for the current user or a specific user (admin only).",
                "operationId": "trustedUserDestroy"
            }
        },
        "/settings/account": {
            "delete": {
                "tags": [
                    "Settings"
                ],
                "summary": "Delete User Account",
                "description": "Deletes the Account for the user and all posts created by it",
                "operationId": "deleteUserAccount",
                "security": [
                    {
                        "passport": [
                            "extra-delete"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/{username}/statuses": {
            "get": {
                "tags": [
                    "User",
                    "Status"
                ],
                "summary": "[Auth optional] Get paginated statuses for single user",
                "description": "Returns paginated statuses of a single user specified by the username",
                "operationId": "getStatusesForUser",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/{username}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "[Auth optional] Get information for single user",
                "description": "Returns general information, metadata and statistics for a user",
                "operationId": "showUser",
                "security": [
                    {
                        "passport": [
                            "read-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/{id}/block": {
            "post": {
                "tags": [
                    "User/Hide and Block"
                ],
                "summary": "Block a user",
                "description": "Block a specific user. That user will not be able to see your statuses or profile information,\n     *      and cannot send you follow requests. Public statuses are still visible through the incognito mode.",
                "operationId": "createBlock",
                "security": [
                    {
                        "passport": [
                            "write-block"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User/Hide and Block"
                ],
                "summary": "Unmute a user",
                "description": "Unblock a specific user. They are now able to see your statuses and profile information again,\n     *      and send you follow requests.",
                "operationId": "destroyBlock",
                "security": [
                    {
                        "passport": [
                            "write-block"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/{id}/mute": {
            "post": {
                "tags": [
                    "User/Hide and Block"
                ],
                "summary": "Mute a user",
                "description": "Mute a specific user. That way they will not be shown on your dashboard and in the active\n     *      journeys tab",
                "operationId": "createMute",
                "security": [
                    {
                        "passport": [
                            "write-block"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User/Hide and Block"
                ],
                "summary": "Unmute a user",
                "description": "Unmute a specific user. That way they will be shown on your dashboard and in the active\n     *      journeys tab again",
                "operationId": "destroyMute",
                "security": [
                    {
                        "passport": [
                            "write-block"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/user/search/{query}": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get paginated statuses for single user",
                "description": "Returns paginated statuses of a single user specified by the username",
                "operationId": "searchUsers",
                "security": [
                    {
                        "passport": [
                            "read-search"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/webhooks": {
            "get": {
                "tags": [
                    "Webhooks"
                ],
                "summary": "Get webhooks for current user and current application",
                "description": "Returns all webhooks which are created for the current user and which the current authorized applicaton has access to.",
                "operationId": "getWebhooks",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/webhooks/{id}": {
            "get": {
                "tags": [
                    "Webhooks"
                ],
                "summary": "Get single webhook",
                "description": "Returns a single webhook Object, if user and application is authorized to see it",
                "operationId": "getSingleWebhook",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Webhooks"
                ],
                "summary": "Delete a webhook if the user and application are authorized to do",
                "description": "",
                "operationId": "deleteWebhook",
                "security": [
                    {
                        "passport": []
                    },
                    {
                        "token": []
                    }
                ]
            }
        },
        "/year-in-review": {
            "get": {
                "tags": [
                    "Statistics"
                ],
                "summary": "Returns the year in review for the given year and authenticated user",
                "description": "Please note: This endpoint is only available when the year in review feature is enabled in the backend configuration. There is no full documentation - this endpoint may change every year.",
                "operationId": "getYearInReview",
                "security": [
                    {
                        "passport": [
                            "create-statuses"
                        ]
                    },
                    {
                        "token": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "passport": {
                "type": "oauth2",
                "description": "OAuth2 authorizationCode Flow. Get your token from https://traewelling.de/settings/applications. Set the redirect URL to https://traewelling.de/api/oauth2-callback to use it here. See also https://laravel.com/docs/9.x/passport",
                "in": "header",
                "scheme": "https",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "http://localhost:8000/oauth/authorize",
                        "tokenUrl": "http://localhost:8000/oauth/token",
                        "refreshUrl": "http://localhost:8000/auth/refresh",
                        "scopes": {
                            "read-statuses": "see all statuses",
                            "read-notifications": "see your notifications",
                            "read-statistics": "see your statistics",
                            "read-search": "search in Träwelling",
                            "write-statuses": "create, edit, delete statuses",
                            "write-likes": "create and remove likes",
                            "write-notifications": "mark notifications as read, clear notifications",
                            "write-exports": "request data exports",
                            "write-follows": "follow and unfollow users",
                            "write-followers": "accept follow requests and remove followers",
                            "write-blocks": "block and unblock users, mute and unmute users",
                            "write-event-suggestions": "suggest events in your name",
                            "write-support-tickets": "create support tickets in your name",
                            "read-settings": "see your settings, email, etc.",
                            "write-settings-profile": "edit your profile",
                            "read-settings-profile": "see your profile data, e.g. email",
                            "write-settings-mail": "edit your email",
                            "write-settings-profile-picture": "edit your profile picture",
                            "write-settings-privacy": "change your privacy settings",
                            "read-settings-followers": "show follow-requests and followers",
                            "write-settings-calendar": "create and delete new calendar-tokens",
                            "extra-write-password": "change your password",
                            "extra-terminate-sessions": "log you out of other sessions and apps",
                            "extra-delete": "delete your account"
                        }
                    }
                }
            },
            "token": {
                "type": "apiKey",
                "description": "Enter token in format \"Bearer \\<token\\>\". You can create your personal access token at https://traewelling.de/settings/applications. We recommend this method for prototyping purposes. For all other use cases please use the oAuth method above.",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "tags": [
        {
            "name": "Auth",
            "description": "Logging in, creating Accounts, etc."
        },
        {
            "name": "Checkin",
            "description": "Checkin related endpoints. Regular process is departures -> trip -> checkin"
        },
        {
            "name": "Dashboard",
            "description": "API Endpoints of Dashboard"
        },
        {
            "name": "Events",
            "description": "Events that users can check in to"
        },
        {
            "name": "Notifications",
            "description": "Get notifications and mark them as read or unread"
        },
        {
            "name": "Status",
            "description": "Endpoints for accessing and manipulating Statusses and their additional data"
        },
        {
            "name": "Likes",
            "description": "Likes regarding a single status"
        },
        {
            "name": "User",
            "description": "Information regarding users"
        },
        {
            "name": "User/Follow",
            "description": "Follow and unfollow users, manage your followers"
        },
        {
            "name": "User/Hide and Block",
            "description": "Mute and block users"
        },
        {
            "name": "Leaderboard",
            "description": "Leaderboard related endpoints"
        },
        {
            "name": "Statistics",
            "description": "Statistics related endpoints"
        },
        {
            "name": "Settings",
            "description": "User/Profile-Settings"
        },
        {
            "name": "Webhooks",
            "description": "Manage Webhooks for third party applications"
        },
        {
            "name": "Report",
            "description": "Report a Status, Event or User to the admins"
        }
    ]
}