version: '3'

services:
  app:
    image: ghcr.io/traewelling/traewelling:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
      - db-rest
    environment:
      - CONTAINER_ROLE=app
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./avatars:/var/www/html/public/uploads/avatars
      - ./storage:/var/www/html/storage

  scheduler:
    image: ghcr.io/traewelling/traewelling:latest
    restart: always
    depends_on:
      - db
      - db-rest
    environment:
      - CONTAINER_ROLE=scheduler
    env_file:
      - .env
    networks:
      - internal

  db:
    image: mariadb:10
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=unsecurepassword
      - MARIADB_DATABASE=traewelling
      - MARIADB_USER=traewelling_u
      - MARIADB_PASSWORD=unsecurepassword
    command:
      - --innodb-buffer-pool-size=2G
      - --innodb-log-file-size=1G
    networks:
      - internal
    volumes:
      - ./database:/var/lib/mysql

  db-rest:
    image: derhuerst/db-rest:5
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    networks:
      - internal

  redis:
    image: redis
    restart: always
    networks:
      - internal

networks:
  internal:
    external: false
