# fly.toml file generated for trwl-develop-environment on 2022-12-02T21:19:56+01:00

app = "trwl-develop-environment"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_NAME = "trwl staging"
  APP_URL = "https://trwl-develop-environment.fly.dev"
  CACHE_DRIVER = "database"
  CONTAINER_ROLE = "launch-all-at-once"
  FORCE_HTTPS = "true"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

  # secrets: APP_KEY, DB_CONNECTION, DB_DATABASE, DB_HOST, DB_PASSWORD, DB_PORT, DB_USERNAME

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
source="trwl_develop_storage"
destination="/var/www/html/storage/app"