name: Bug report
description: Something is not working
title: "Description of the issue"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
      placeholder: |
        Träwelling is not working as expected when I try to ...

        [Screenshot if possible, censor personal data!]
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: browser_logs
    attributes:
      label: Browser console logs
      description: Logs / Errors from the web browser console related to your issue, if needed
      render: bash
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser you are using, if relevant.
      placeholder: e.g. Chrome, Safari
