version: '3'

services:
  app:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-app
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
      - db-rest
    environment:
      - CONTAINER_ROLE=app
#      - SEED_DB=true
    env_file:
      - .env.app
    networks:
      - internal
#    volumes:
#      - ./avatars:/var/www/html/public/uploads/avatars
#      - ./storage:/var/www/html/storage

  scheduler:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-scheduler
    restart: always
    depends_on:
      - db
      - db-rest
    environment:
      - CONTAINER_ROLE=scheduler
    env_file:
      - .env.app
    networks:
      - internal

  queue:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-queue
    restart: always
    depends_on:
      - db
      - db-rest
    environment:
      - CONTAINER_ROLE=queue
    env_file:
      - .env.app
    networks:
      - internal

  db:
    image: mariadb:10
    container_name: traewelling-db
    restart: always
    env_file:
      - .env.db
    command:
      - --innodb-buffer-pool-size=2G
      - --innodb-log-file-size=1G
    networks:
      - internal
    volumes:
      - ./database:/var/lib/mysql

  db-rest:
    image: derhuerst/db-rest:5
    container_name: db-rest
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    networks:
      - internal

  redis:
    image: redis
    container_name: db-rest-redis
    restart: always
    networks:
      - internal

networks:
  internal:
    external: false
