# THIS FILE IS NOT DEPLOYED AUTOMATICALLY AND NEEDS A MANUAL PUSH!

app = "trwl-develop-mysql"
kill_signal = "SIGINT"
kill_timeout = 5

[mounts]
  source="trwl_develop_mysqldata"
  destination="/data"

[env]
  MYSQL_DATABASE = "traewelling"
  MYSQL_USER = "traewelling"

  # secrets: MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD

[build]
  image = "mysql:8"

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", "/data/mysql",
    "--performance-schema=OFF",
    "--innodb-buffer-pool-size", "64M"
  ]