[program:trwl-worker-realtime]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/traewelling-prod/artisan queue:work --sleep=1 --max-time=3600 --queue=realtime
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/traewelling-prod/storage/logs/worker-realtime.log
stopwaitsecs=3600

[program:trwl-worker-important]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/traewelling-prod/artisan queue:work --sleep=3 --max-time=3600 --queue=important
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/traewelling-prod/storage/logs/worker-important.log
stopwaitsecs=3600

[program:trwl-worker-normal]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/traewelling-prod/artisan queue:work --sleep=3 --max-time=3600 --queue=normal
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/traewelling-prod/storage/logs/worker-normal.log
stopwaitsecs=3600

[program:trwl-worker-low]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/traewelling-prod/artisan queue:work --sleep=5 --max-time=3600 --queue=low
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/traewelling-prod/storage/logs/worker-low.log
stopwaitsecs=3600

[program:trwl-worker-background]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/traewelling-prod/artisan queue:work --sleep=10 --max-time=3600 --queue=background
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/traewelling-prod/storage/logs/worker-background.log
stopwaitsecs=3600

[group:trwl-workers]
programs=trwl-worker-realtime,trwl-worker-important,trwl-worker-normal,trwl-worker-low,trwl-worker-background
