name: Check if PR title starts with a Gitmoji

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR title starts with emoji or emoji string
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title;
            const emojis = ["🎨","⚡️","🔥","🐛","🚑️","✨","📝","🚀","💄","🎉","✅","🔒️","🔐","🔖","🚨","🚧","💚","⬇️","⬆️","📌","👷","📈","♻️","➕","➖","🔧","🔨","🌐","✏️","💩","⏪️","🔀","📦️","👽️","🚚","📄","💥","🍱","♿️","💡","🍻","💬","🗃️","🔊","🔇","👥","🚸","🏗️","📱","🤡","🥚","🙈","📸","⚗️","🔍️","🏷️","🌱","🚩","🥅","💫","🗑️","🛂","🩹","🧐","⚰️","🧪","👔","🩺","🧱","🧑‍💻","💸","🧵","🦺","✈️"];
            const hasGitmoji = emojis.some(emoji => title.startsWith(emoji));
            if (!hasGitmoji) {
              core.setFailed('❌ PR title does not start with a Gitmoji! 😞');
              return;
            }
            
            console.log('✅ PR title starts with a Gitmoji! 🎉');
